# Generated by Django 3.2.9 on 2022-01-22 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.TextField(choices=[('DEPT_HEAD_CREATE_NEW_APPLICATION', 'Step 1'), ('ADMIN_VERIFY_APPLICATION', 'Step 2'), ('CHAIR_HEAD_APPROVE_APPLICATION', 'Step 3')], max_length=70)),
                ('step_data', models.JSONField(max_length=1000)),
                ('can_update', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('minor', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('patch', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='core.profile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='core.profile')),
                ('current_step', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.applicationstep')),
                ('desired_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='core.rank')),
            ],
        ),
    ]
