# Generated by Django 3.2.9 on 2022-04-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstep',
            name='step_name',
            field=models.TextField(choices=[('APPLICATION_CLOSE', 'Step 0'), ('DEPT_HEAD_CREATE_NEW_APPLICATION', 'Step 1'), ('ADMIN_FEEDBACK', 'Step 2'), ('ADMIN_VERIFY_APPLICATION', 'Step 3'), ('CHAIR_HEAD_FEEDBACK', 'Step 4'), ('CHAIR_HEAD_APPROVE_APPLICATION', 'Step 5')], max_length=70),
        ),
    ]
