# Generated by Django 3.2.9 on 2022-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
