# Generated by Django 3.2.9 on 2022-05-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220508_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='joined_date',
        ),
    ]
