# Generated by Django 3.2.9 on 2022-05-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_date_profile_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='core.department'),
        ),
        migrations.AddField(
            model_name='applicationstep',
            name='currentStep',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationstep',
            name='step_name',
            field=models.TextField(choices=[('APPLICATION_CLOSE', 'Step 0'), ('DEPT_HEAD_CREATE_NEW_APPLICATION', 'Step 1'), ('DEPT_HEAD_FEEDBACK', 'Step 2'), ('ADMIN_FEEDBACK', 'Step 3'), ('ADMIN_VERIFY_APPLICATION', 'Step 4'), ('CHAIR_HEAD_FEEDBACK', 'Step 5'), ('CHAIR_HEAD_APPROVE_APPLICATION', 'Step 6')], max_length=70),
        ),
    ]
