# Generated by Django 3.2.9 on 2022-05-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220512_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstep',
            name='currentStep',
            field=models.BooleanField(default=False),
        ),
    ]
