# Generated by Django 3.2.9 on 2022-05-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_applicationstep_currentstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.TextField(choices=[("פרופ'", 'Prof'), ('מר.', 'Mr'), ("גב'", 'Mis'), ('ד"ר', 'Doc')], default=None, max_length=50),
        ),
    ]
