# Generated by Django 3.2.9 on 2022-06-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applicationstep',
            name='step_name',
            field=models.TextField(choices=[('APPLICATION_CLOSE', 'Step 0'), ('DEPT_HEAD_CREATE_NEW_APPLICATION', 'Step 1'), ('DEPT_HEAD_FEEDBACK', 'Step 2'), ('ADMIN_FEEDBACK', 'Step 3'), ('ADMIN_VERIFY_APPLICATION', 'Step 4'), ('CHAIR_HEAD_FEEDBACK', 'Step 5'), ('CHAIR_HEAD_APPROVE_APPLICATION', 'Step 6'), ('QUALITY_DEPT_UPLOAD_FILES', 'Step 7')], max_length=70),
        ),
    ]
