# Generated by Django 3.2.9 on 2022-06-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_application_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uploaded_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
