# Generated by Django 3.2.9 on 2022-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_uploaded_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uploaded_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
