# Generated by Django 3.2.9 on 2022-06-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_application_uploaded_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='uploaded_time',
        ),
    ]
